### ISSUE TITLE
Store endpoint url in variable for better readability and reusability

### ISSUE THREAD

**Issue by joostf** [boudewijnbout/the-web-is-for-everyone-chippr.dev#10]
https://github.com/boudewijnbout/the-web-is-for-everyone-chippr.dev/blob/57e001dd0f2342e482900b0ed3b4b35c2ff8d5eb/routes/projects.js#L8

https://github.com/boudewijnbout/the-web-is-for-everyone-chippr.dev/blob/57e001dd0f2342e482900b0ed3b4b35c2ff8d5eb/routes/projects.js#L17

**Comment by boudewijnbout** [comment]
Created seperate `let apiUrl` for the base api link.
