### ISSUE TITLE
Consider using plural: projectRoutes

### ISSUE THREAD

**Issue by joostf** [boudewijnbout/the-web-is-for-everyone-chippr.dev#11]
https://github.com/boudewijnbout/the-web-is-for-everyone-chippr.dev/blob/57e001dd0f2342e482900b0ed3b4b35c2ff8d5eb/app.js#L11

The module handles multiple routes, so plural seems more logical?!

**Comment by boudewijnbout** [comment]
Thanks for the heads-up. Changed to projectsRoute.
